import React, { useRef, useEffect, useState } from 'react';
import { X, Printer, Download, Shield, Mail, Calendar, User, Clock, FileText } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const ReportPreviewModal = ({
  isOpen,
  onClose,
  title = 'System Report',
  generatedBy = 'System Administrator',
  personInCharge = '',
  stats = [],
  tableHeaders = [],
  tableData = [],
  secondTableHeaders = null,
  secondTableData = null,
  secondTableTitle = '',
  pdfFilename = 'report.pdf',
  schoolYear = '',
  proofImages = []
}) => {
  const logoRef = useRef(null);
  const [logoBase64, setLogoBase64] = useState(null);
  const [preloadedImages, setPreloadedImages] = useState([]);

  // Preload and convert proof images to base64
  const proofImagesString = JSON.stringify(proofImages);
  useEffect(() => {
    if (isOpen && proofImages && proofImages.length > 0) {
      const loadImages = async () => {
        const loaded = await Promise.all(
          proofImages.map(async (img) => {
            return new Promise((resolve) => {
              const image = new Image();
              image.crossOrigin = 'anonymous';
              image.src = img.file_url || img.url;
              image.onload = () => {
                try {
                  const canvas = document.createElement('canvas');
                  canvas.width = image.naturalWidth || image.width;
                  canvas.height = image.naturalHeight || image.height;
                  const ctx = canvas.getContext('2d');
                  ctx.drawImage(image, 0, 0);
                  const base64 = canvas.toDataURL('image/jpeg', 0.7);
                  resolve({ base64, name: img.file_name || img.name || 'Proof Image' });
                } catch (err) {
                  console.error('Failed to convert proof image to base64:', err);
                  resolve(null);
                }
              };
              image.onerror = () => {
                resolve(null);
              };
            });
          })
        );
        setPreloadedImages(loaded.filter(Boolean));
      };
      loadImages();
    } else {
      setPreloadedImages([]);
    }
  }, [isOpen, proofImagesString]);


  // Convert logo.png to base64 for jsPDF once it's loaded in the browser DOM
  const convertLogoToBase64 = () => {
    const img = logoRef.current;
    if (img && img.complete) {
      try {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth || img.width;
        canvas.height = img.naturalHeight || img.height;
        const ctx = canvas.getContext('2d');
        ctx.drawImage(img, 0, 0);
        const base64 = canvas.toDataURL('image/png');
        setLogoBase64(base64);
      } catch (err) {
        console.error('Failed to convert logo to base64:', err);
      }
    }
  };

  useEffect(() => {
    if (isOpen) {
      convertLogoToBase64();
      const timer = setTimeout(convertLogoToBase64, 500);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const timestamp = new Date().toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    // PDF page sizes in mm: A4 is 210 x 297
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    let currentY = 28; // Header separator is at Y=24

    // 1. Title Block
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(16, 82, 32); // Primary Green
    const titleLines = doc.splitTextToSize(title.toUpperCase(), 185);
    doc.text(titleLines, 105, currentY, { align: 'center' });
    currentY += (titleLines.length * 5.5) + 3;

    // 2. Metadata Block
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(55, 65, 81); // Dark Gray
    doc.text(`Generated Date: ${timestamp}`, 10, currentY);
    doc.text(`Generated By: ${generatedBy}`, 10, currentY + 4.5);
    
    let nextYOffset = 9;
    if (personInCharge) {
      doc.text(`Person in Charge: ${personInCharge}`, 10, currentY + nextYOffset);
      nextYOffset += 4.5;
    }
    if (schoolYear) {
      doc.text(`School Year: ${schoolYear}`, 10, currentY + nextYOffset);
      nextYOffset += 4.5;
    }
    currentY += nextYOffset + 3;

    // 3. Stats Cards
    if (stats && stats.length > 0) {
      const statsCount = stats.length;
      const totalWidth = 190; // 210 - 20 margin
      const gap = 3;
      const cardWidth = (totalWidth - (statsCount - 1) * gap) / statsCount;
      const cardHeight = 16;

      stats.forEach((stat, idx) => {
        const cardX = 10 + idx * (cardWidth + gap);
        const cardY = currentY;

        // Gray Box
        doc.setFillColor(243, 244, 246);
        doc.roundedRect(cardX, cardY, cardWidth, cardHeight, 1.5, 1.5, 'F');

        // Draw Accent Line
        doc.setFillColor(16, 82, 32);
        doc.rect(cardX, cardY, 1.5, cardHeight, 'F');

        // Stat Label
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(6.5);
        doc.setTextColor(107, 114, 128);
        doc.text(stat.label.toUpperCase(), cardX + 3.5, cardY + 5);

        // Stat Value
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(17, 24, 39);
        doc.text(String(stat.value), cardX + 3.5, cardY + 12);
      });
      currentY += cardHeight + 8;
    }

    // 4. Primary Table
    autoTable(doc, {
      startY: currentY,
      head: [tableHeaders],
      body: tableData,
      theme: 'striped',
      headStyles: {
        fillColor: [16, 82, 32], // Primary Green
        textColor: [255, 255, 255],
        fontSize: 8.5,
        fontStyle: 'bold',
        halign: 'left'
      },
      bodyStyles: {
        fontSize: 7.5,
        textColor: [31, 41, 55]
      },
      alternateRowStyles: {
        fillColor: [249, 250, 251]
      },
      margin: { top: 26, left: 10, right: 10, bottom: 25 },
    });

    currentY = doc.lastAutoTable.finalY + 10;

    // 5. Secondary Table (If applicable)
    if (secondTableHeaders && secondTableData) {
      // Check if we need a new page for secondary table header
      if (currentY > 240) {
        doc.addPage();
        currentY = 28;
      }

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(16, 82, 32);
      doc.text(secondTableTitle || 'Details Logs', 10, currentY);
      currentY += 4;

      autoTable(doc, {
        startY: currentY,
        head: [secondTableHeaders],
        body: secondTableData,
        theme: 'striped',
        headStyles: {
          fillColor: [75, 85, 99], // Slate/gray header
          textColor: [255, 255, 255],
          fontSize: 8.5,
          fontStyle: 'bold',
          halign: 'left'
        },
        bodyStyles: {
          fontSize: 7.5,
          textColor: [31, 41, 55]
        },
        margin: { top: 26, left: 10, right: 10, bottom: 25 },
      });
    }

    // 5.5 Proof of Implementation Images (PDF drawing)
    if (preloadedImages && preloadedImages.length > 0) {
      doc.addPage();
      currentY = 28;

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(11);
      doc.setTextColor(16, 82, 32);
      doc.text('PROOF OF ACTIVITY IMPLEMENTATION', 10, currentY);
      currentY += 8;

      preloadedImages.forEach((img, idx) => {
        const isSecondOnPage = idx % 2 === 1;
        if (idx > 0 && !isSecondOnPage) {
          doc.addPage();
          currentY = 28;
          
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(11);
          doc.setTextColor(16, 82, 32);
          doc.text('PROOF OF ACTIVITY IMPLEMENTATION (CONTINUED)', 10, currentY);
          currentY += 8;
        }

        const imageY = isSecondOnPage ? 140 : currentY;
        const imageHeight = 85;
        const imageWidth = 130;
        const imageX = 40; // center it (210 - 130) / 2 = 40

        try {
          doc.addImage(img.base64, 'JPEG', imageX, imageY, imageWidth, imageHeight);
          
          // Add label below image
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(8);
          doc.setTextColor(107, 114, 128);
          doc.text(img.name.toUpperCase(), 105, imageY + imageHeight + 5, { align: 'center' });
        } catch (err) {
          console.error('Error drawing image in PDF:', err);
        }

        if (!isSecondOnPage) {
          currentY = imageY + imageHeight + 15;
        }
      });
    }

    // 6. Running Header and Footer (Drawn on all pages)
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      
      // Header Logo & Institutional Title
      if (logoBase64) {
        doc.addImage(logoBase64, 'PNG', 10, 7, 14, 14);
      }
      doc.setTextColor(16, 82, 32); // Primary Green
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('BULACAN STATE UNIVERSITY', 27, 11);
      
      doc.setTextColor(55, 65, 81); // Dark Gray
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.text('BUSTOS CAMPUS', 27, 15);
      doc.text('OFFICE OF STUDENT ORGANIZATIONS (OSODOCS)', 27, 18.5);
      
      // Decorative Header line
      doc.setDrawColor(16, 82, 32);
      doc.setLineWidth(0.35);
      doc.line(10, 22, 200, 22);

      // Running Footer
      doc.setDrawColor(229, 231, 235);
      doc.line(10, 280, 200, 280);

      doc.setFontSize(7.5);
      doc.setTextColor(156, 163, 175);
      doc.text('BulSU Bustos OSODOCS System-generated Report', 10, 285);
      doc.text(`Page ${i} of ${pageCount}`, 200, 285, { align: 'right' });
    }

    // Save File
    doc.save(pdfFilename);
  };

  return (
    <div 
      className="fixed inset-0 bg-slate-900/85 z-[999999] flex flex-col items-center justify-center p-3 sm:p-6 backdrop-blur-md overflow-hidden font-sans text-gray-800"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      {/* Hidden original logo in the DOM for canvas conversion */}
      <img
        ref={logoRef}
        src="/logo.png"
        className="hidden"
        alt="Logo Canvas Source"
        onLoad={convertLogoToBase64}
      />

      <div className="bg-white w-full max-w-4xl rounded-2xl sm:rounded-3xl shadow-2xl flex flex-col h-[92vh] sm:h-[88vh] overflow-hidden border border-gray-100" onClick={e => e.stopPropagation()}>
        {/* Sticky Actions Bar */}
        <div className="bg-white border-b border-gray-100 px-4 sm:px-6 py-3 sm:py-4 flex items-center justify-between gap-3 shrink-0 no-print w-full">
          <div className="min-w-0 flex-1">
            <h3 className="font-extrabold text-gray-900 text-sm sm:text-lg uppercase tracking-tight line-clamp-1">Report Document Preview</h3>
            <p className="text-gray-400 text-[10px] sm:text-xs font-semibold hidden sm:block">Verify the data before printing or exporting to PDF.</p>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 sm:px-4 py-2 sm:py-2 bg-gray-50 hover:bg-gray-100 text-gray-700 text-[11px] sm:text-xs font-black rounded-xl transition-all uppercase tracking-wider border border-gray-200"
            >
              <Printer size={14} />
              <span className="hidden sm:inline">Print</span>
            </button>
            <button
              onClick={handleDownloadPDF}
              className="flex items-center gap-1.5 px-3 sm:px-5 py-2 sm:py-2 bg-primary-green hover:brightness-110 text-white text-[11px] sm:text-xs font-black rounded-xl transition-all uppercase tracking-wider shadow-md shadow-primary-green/20"
            >
              <Download size={14} />
              <span>Download PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 text-gray-400 hover:text-gray-700 hover:bg-gray-100 rounded-full transition-colors shrink-0 ml-1"
              title="Close modal"
              aria-label="Close modal"
            >
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Scrollable Preview Paper Sheet Container */}
        <div className="flex-1 overflow-auto bg-gray-100/50 p-2 sm:p-8 flex justify-center items-start scrollbar-thin">
          <div className="w-[794px] shrink-0 origin-top scale-[0.41] min-[380px]:scale-[0.47] min-[440px]:scale-[0.55] sm:scale-[0.72] md:scale-[0.85] lg:scale-100 mb-[-640px] min-[380px]:mb-[-560px] min-[440px]:mb-[-470px] sm:mb-[-300px] md:mb-[-160px] lg:mb-0">
            {/* Printable A4 Simulated Sheet */}
            <div
              id="print-report-preview"
              className="bg-white w-[794px] min-h-[297mm] px-6 sm:px-[10mm] py-6 sm:py-[20mm] shadow-lg border border-gray-200/50 rounded-lg text-gray-800 flex flex-col font-sans relative"
            >
              {/* 1. Header Area */}
              <div className="flex items-center gap-4 border-b-2 border-primary-green pb-4 mb-6">
                <img
                  src="/logo.png"
                  className="w-14 h-14 object-contain shrink-0"
                  alt="BulSU Logo"
                />
                <div>
                  <h1 className="text-primary-green font-black text-base uppercase tracking-wide leading-tight">Bulacan State University</h1>
                  <p className="text-gray-600 font-bold text-xs">BUSTOS CAMPUS</p>
                  <p className="text-gray-500 font-medium text-[11px] uppercase tracking-wider">Office of Student Organizations (OSODOCS)</p>
                </div>
              </div>

              {/* 2. Title & Metadata */}
              <div className="text-center mb-6">
                <h2 className="text-base sm:text-xl font-extrabold text-gray-900 uppercase tracking-wide border-b border-gray-100 pb-2 inline-block px-4 sm:px-8 break-words">
                  {title}
                </h2>
              </div>
              
              <div className="flex flex-col sm:flex-row justify-between items-start text-xs text-gray-500 mb-6 sm:mb-8 bg-gray-50/50 p-3 sm:p-4 rounded-xl border border-gray-100 gap-3">
                <div>
                  <p className="font-semibold text-gray-700">Generated By:</p>
                  <p className="font-bold text-primary-green mt-0.5 text-sm">{generatedBy}</p>
                  {schoolYear && (
                    <>
                      <p className="font-semibold text-gray-700 mt-2">School Year:</p>
                      <p className="font-bold text-gray-800 mt-0.5">{schoolYear}</p>
                    </>
                  )}
                </div>
                {personInCharge && (
                  <div>
                    <p className="font-semibold text-gray-700">Person in Charge:</p>
                    <p className="font-bold text-gray-900 mt-0.5 text-sm">{personInCharge}</p>
                  </div>
                )}
                <div className="text-right">
                  <p className="font-semibold text-gray-700">Date Generated:</p>
                  <p className="font-bold text-gray-800 mt-0.5">{timestamp}</p>
                </div>
              </div>

              {/* 3. Stats Section */}
              {stats && stats.length > 0 && (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
                  {stats.map((stat, idx) => (
                    <div key={idx} className="bg-[#F8F9FA] p-3.5 rounded-xl border border-gray-200/60 flex flex-col justify-between border-l-2 border-l-primary-green">
                      <span className="text-[9px] font-semibold text-gray-500 uppercase tracking-wider leading-none mb-2">{stat.label}</span>
                      <span className="text-base font-bold text-gray-800 leading-tight mt-1">{stat.value}</span>
                    </div>
                  ))}
                </div>
              )}

              <div className="mb-8">
                <table className={`w-full text-left border-collapse text-xs border border-gray-200 ${tableHeaders.length === 2 ? 'table-fixed' : ''}`}>
                  <thead>
                    <tr className="bg-[#073c2d] text-white font-bold">
                      {tableHeaders.map((head, idx) => (
                        <th key={idx} className="px-4 py-2.5 uppercase tracking-wider text-[9px] first:rounded-tl-lg last:rounded-tr-lg border-b border-[#073c2d] font-semibold text-white">
                          {head}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 bg-white">
                    {tableData.map((row, rIdx) => {
                      const isKeyValueTable = tableHeaders.length === 2;
                      return (
                        <tr key={rIdx} className="hover:bg-gray-50 transition-colors odd:bg-gray-50/10">
                          {row.map((cell, cIdx) => {
                            if (isKeyValueTable && cIdx === 0) {
                              return (
                                <td key={cIdx} className="px-4 py-2.5 text-gray-500 font-semibold text-[10px] uppercase tracking-wider bg-gray-50/50 w-1/5 select-none border-b border-gray-100">
                                  {cell}
                                </td>
                              );
                            }
                            const isStatusCol = cIdx === row.length - 1;
                            return (
                              <td key={cIdx} className={`px-4 py-2.5 text-gray-600 border-b border-gray-100 ${isStatusCol ? 'whitespace-nowrap font-bold text-emerald-800' : 'break-words'} ${isKeyValueTable ? 'font-normal text-xs' : 'font-medium text-xs'}`}>
                                {cell}
                              </td>
                            );
                          })}
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

            {/* 5. Secondary Data Table (Timeline/History for Detail view) */}
            {secondTableHeaders && secondTableData && (
              <div className="mt-4 mb-8 page-break-before">
                <h3 className="text-xs font-bold text-primary-green uppercase tracking-wider mb-3">
                  {secondTableTitle || 'Detail Timeline Audit Logs'}
                </h3>
                <table className={`w-full text-left border-collapse text-xs border border-gray-200 ${secondTableHeaders.length === 2 ? 'table-fixed' : ''}`}>
                  <thead>
                    <tr className="bg-[#073c2d] text-white font-semibold">
                      {secondTableHeaders.map((head, idx) => (
                        <th key={idx} className="px-4 py-2.5 uppercase tracking-wider text-[9px] border-b border-[#073c2d] font-semibold text-white">
                          {head}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-100 bg-white">
                    {secondTableData.map((row, rIdx) => (
                      <tr key={rIdx} className="hover:bg-gray-50 transition-colors odd:bg-gray-50/10">
                        {row.map((cell, cIdx) => (
                          <td key={cIdx} className="px-4 py-2.5 text-gray-600 font-normal text-xs whitespace-pre-line break-all break-words max-w-0 border-b border-gray-100">
                            {cell}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {/* Proof of Activity Implementation Images */}
            {proofImages && proofImages.length > 0 && (
              <div className="mt-8 mb-8 page-break-before">
                <h3 className="text-sm font-extrabold text-primary-green uppercase tracking-wider mb-4 border-b-2 border-primary-green pb-2">
                  Proof of Activity Implementation
                </h3>
                <div className="grid grid-cols-2 gap-4">
                  {proofImages.map((img, idx) => (
                    <div key={idx} className="flex flex-col items-center p-2 border border-gray-100 rounded-xl bg-gray-50/50">
                      <img
                        src={img.file_url || img.url}
                        alt={img.file_name || `Proof Image ${idx + 1}`}
                        className="max-h-48 object-contain rounded-lg border border-gray-200 bg-white"
                        crossOrigin="anonymous"
                      />
                      <span className="text-[10px] font-bold text-gray-400 mt-2 uppercase tracking-wide text-center truncate w-full">
                        {img.file_name || `Proof Image ${idx + 1}`}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* 6. Running Footer inside the simulated page */}
            <div className="mt-auto border-t border-gray-200 pt-4 flex justify-between items-center text-[10px] text-gray-400 no-print">
              <span>CONFIDENTIAL - FOR INTERNAL BULSU OSODOCS USE ONLY</span>
              <span>BulSU Bustos OSODOCS System Generated</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
);
};

export default ReportPreviewModal;
